# Generated by Django 5.0.4 on 2024-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
