# Generated by Django 5.0.4 on 2024-04-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
