# Generated by Django 5.0.4 on 2024-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='movie_service.category'),
        ),
    ]
